{% set name = "catalystcoop.pudl_catalog" %}
{% set version = "2022.11.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/catalystcoop.pudl_catalog-{{ version }}.tar.gz
  sha256: dd6eb51d3c1a7d781b7585657b55fc8ba4589da74a1aac2d016050cd2b3c8276

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - python >={{ python_min }},<3.12
    - gcsfs >=2021.7,<2022.11.1
    - intake-parquet >=0.2.3,<0.3
    - intake-sqlite >=0.2.0
    - msgpack-python >=1,<2
    - boto3 ==1.24.59
    - s3fs >=2021.7,<2022.11.1

test:
  imports:
    - pudl_catalog
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/catalyst-cooperative/pudl-catalog
  summary: A catalog of open data related to the US energy system.
  doc_url: https://catalystcoop-pudl-catalog.readthedocs.io
  dev_url: https://github.com/catalyst-cooperative/pudl-catalog
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - zaneselvans
